#!/bin/bash

# Ensure the script has execute permissions
chmod +x "$0"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_colored() {
    echo -e "$1$2${NC}"
}

run_task() {
    local task=$1
    local start_time end_time elapsed_time

    start_time=$(./bash/timer start)
    if $task; then
        end_time=$(./bash/timer end)
        elapsed_time=$(( (end_time - start_time) / 1000000 )) # Convert nanoseconds to milliseconds
        print_colored "$GREEN" "Task '$task' successful in ${elapsed_time} milliseconds."
    else
        end_time=$(./bash/timer end)
        elapsed_time=$(( (end_time - start_time) / 1000000 )) # Convert nanoseconds to milliseconds
        print_colored "$RED" "Task '$task' failed in ${elapsed_time} milliseconds."
    fi
}

if [ $# -eq 0 ]; then
    CPP_FILE="main.cpp"
    EXECUTABLE="./main"
    print_colored "$BLUE" "No path provided. Defaulting to compile and run 'main.cpp'."
else
    CPP_FILE=$1
    EXECUTABLE="./${CPP_FILE%.*}"
fi

if [ ! -f "$CPP_FILE" ]; then
    print_colored "$RED" "File $CPP_FILE does not exist."
    exit 1
fi

# Remove the old executable if it exists
if [ -f "$EXECUTABLE" ]; then
    print_colored "$BLUE" "Removing old executable '$EXECUTABLE'."
    rm -f "$EXECUTABLE"
fi

mkdir -p ./bash

print_colored "$BLUE" "Trying to compile $CPP_FILE."
run_task "g++ -o $EXECUTABLE $CPP_FILE"

if [ $? -ne 0 ]; then
    print_colored "$RED" "Compilation failed. Cannot run $EXECUTABLE."
    exit 1
fi

# Ensure the compiled executable has execute permissions
chmod +x "$EXECUTABLE"
print_colored "$BLUE" "Executable '$EXECUTABLE' is now executable."

print_colored "$BLUE" "Trying to run $EXECUTABLE."
run_task "$EXECUTABLE"

print_colored "$BLUE" "Deleting $EXECUTABLE."
rm -f "$EXECUTABLE"
